spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://auth-service-postgres:5432/auth_db
    driver-class-name: org.postgresql.Driver
  mail:
    username: filmygliko535@gmail.com
    password: fkhu hgdp edwy uihy
  messages:
    encoding: UTF-8
    basename: messages
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
integration:
  user-service:
    name: user-service
    max-attempts: 3
    delay: 500
management:
  endpoints:
    web:
      exposure:
        include: health