spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  mail:
    username: filmygliko@gmail.com
    password: erry rmnp wvik cbki
  messages:
    encoding: UTF-8
    basename: messages
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
integration:
  user-service:
    name: user-service
    max-attempts: 3
    delay: 500