version: '3.8'
services:
  auth-service-postgres:
    image: postgres:16
    container_name: auth-service-postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"